version: '3.8'

services:
  frontend:
    build:
      context: ./polygon-app
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: ./PolygonApp
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge